# Generated by Django 5.1.5 on 2025-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
