# Generated by Django 5.1.5 on 2025-01-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tours_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='category',
        ),
        migrations.AddField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(related_name='tours', to='tour.tourcategory'),
        ),
    ]
