# Generated by Django 5.1.5 on 2025-01-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tourcategory_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
