# Generated by Django 5.1.5 on 2025-01-16 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tour.tours')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
