# Generated by Django 5.1.5 on 2025-01-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_request_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='tour',
        ),
    ]
